### ISSUE TITLE
Crash When Placing Furnace from Above

### ISSUE THREAD

**Issue by Rahmiel** [Draylar/fabric-furnaces#9]
As the title says. Originally I had an issue breaking furnaces from your mod, but you updated, so I tried testing your mod again. Now I crash when I attempting to place the furnace down from above (creative mode, not tested in survival). I really like the idea of this mod, it feels mostly vanilla, and would make a great addition to any Vanilla+ pack on Fabric, especially with pipes and such.

Crash Log: https://paste.ee/p/r2Qdq

Edit1: Testing in survival (jump placing) causes the issue as well. From what I can read in the log it has something to do with a property, it says that only North, South, East, and West are allowed for 'facing' again I know little of coding especially with fabric so I'm just trying to get a good pinpoint.

Crash Log in Survival (probably the same): https://paste.ee/p/2qmd3

Edit2: I forgot to turn off FoamFix (it can cause issues with crash logs sometimes, though I don't think it did this time) So just in case.

Crash Log in Survival no FoamFix: https://paste.ee/p/FlOXq

**Comment by Draylar** [comment]
Hi Rahmiel, thanks for the detailed report. Much appreciated!

`getPlayerHorizontalFacing` was remapped in 1.14.3. I assumed the new method was `getPlayerLookDirection`, but it was actually `getPlayerFacing`. The first method accounted for all _6_ sides, while the second only accounts for horizontal directions. The furnaces can't be placed up or down so it crashed as you guessed.

Fixed in 1.1.7 which will be out in a second. Thanks again!

**Comment by Rahmiel** [comment]
Just for a closing statement, thanks a lot for this! So far this is the best response I've had from a developer since I started modding minecraft (back in 1.7 beta). Keep up the great work, and keep making Fabric a competitor with your mods.
